version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"


  library:
    image: library
    container_name: library system
    restart: on-failure
    build: src/library system
    ports:
      - "8060:8060"
    depends_on:
      - postgres
      -
  reservation:
    image: reservation
    container_name: reservation system
    restart: on-failure
    build: ./src/reservation system
    ports:
      - "8070:8070"
    depends_on:
      - postgres


volumes:
  db-data: